# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.json'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.json'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [ 8 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew check
